export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'


export const LC_CREATE_SUCCESS = 'LC_CREATE_SUCCESS'
export const LC_CREATE_FAILURE = 'LC_CREATE_FAILURE'

export const LC_READ_SUCCESS = 'LC_READ_SUCCESS'
export const LC_READ_FAILURE = 'LC_READ_FAILURE'

export const LC_UPDATE_SUCCESS = 'LC_UPDATE_SUCCESS'
export const LC_UPDATE_FAILURE = 'LC_UPDATE_FAILURE'

export const LC_DELETE_SUCCESS = 'LC_DELETE_SUCCESS'
export const LC_DELETE_FAILURE = 'LC_DELETE_FAILURE'


export const LC_READ_ALL_SUCCESS = 'LC_READ_ALL_SUCCESS'
export const LC_READ_ALL_FAILURE = 'LC_READ_ALL_FAILURE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'